q = {
    1: ["A", "B", "C", "CBD", "AB", "CAE", "AB", "CB"],
    2: ["C", "G", "BG", "DG", "BG"],
    3: ["C", "A", "DEF", "AE"],
    4: [
        "DEF",
        "DFE",
        "E",
        "DE",
        "DF",
        "EDF",
        "F",
        "DF",
        "E",
        "EF",
        "EF",
        "DEF",
    ],
    5: [
        "CE",
        "ACB",
        "BCE",
        "BD",
        "AG",
        "FAG",
        "AGB",
        "AG",
        "BC",
    ],
    6: [
        "DC",
        "ACB",
        "AB",
        "ACB",
    ],
    7: ["AB", "DA", "DB", "ADC", "DCB"],
    8: ["EDF", "E", "EF", "F", "ED", "DF"],
    9: ["DE", "AF", "AE", "AF", "EF"],
    10: ["CB", "DB", "D"],
    11: [
        "FDE",
        "CF",
        "FE",
        "ECF",
    ],
    12: ["EFG", "CD", "H", "CH"],
    13: ["EBD", "ABE", "EBA", "ABC"],
    14: ["BC", "ABE", "ABD"],
    15: ['DEB', 'CEB'],
    16: ['ECD'],
    17: ["D"],
    18: ['DCB', 'ACB', 'ACB'],
    19: ['ABC', 'AC', 'ACB', 'ACB'],
    20: ['BA', 'AC', 'BC', 'AB', 'BC', 'AC', 'BC', 'CA', 'AB']
}
